package com.itucity.dsmp.identity.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GroupPO generated by hbm2java
 */
@Entity
@Table(name = "bs_group")
public class GroupPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5932013271876354570L;
	private Integer groupId;
	private String groupName;
	private String type;
	private Integer parentId;
	private String remarks;

	public GroupPO() {
	}

	public GroupPO(String groupName, String type, Integer parentId,
			String remarks) {
		this.groupName = groupName;
		this.type = type;
		this.parentId = parentId;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "group_id", unique = true, nullable = false)
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "group_name", length = 30)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "type", length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Override
	public String toString() {
		return "GroupPO [groupId=" + groupId + ", groupName=" + groupName
				+ ", type=" + type + ", parentId=" + parentId + ", remarks="
				+ remarks + "]";
	}

}
