package com.itucity.dsmp.identity.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TokenPO generated by hbm2java
 */
@Entity
@Table(name = "bs_token")
public class TokenPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5571856907689230164L;
	private Integer tokenId;
	private String token;
	private String refreshToken;
	private Date expiresIn;
	private Integer uid;

	public TokenPO() {
	}

	public TokenPO(Integer uid) {
		this.uid = uid;
	}

	public TokenPO(String token, String refreshToken, Date expiresIn, Integer uid) {
		this.token = token;
		this.refreshToken = refreshToken;
		this.expiresIn = expiresIn;
		this.uid = uid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "token_id", unique = true, nullable = false)
	public Integer getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(Integer tokenId) {
		this.tokenId = tokenId;
	}

	@Column(name = "token", length = 30)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "refresh_token", length = 30)
	public String getRefreshToken() {
		return this.refreshToken;
	}

	public void setRefreshToken(String refreshToken) {
		this.refreshToken = refreshToken;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expires_in", length = 19)
	public Date getExpiresIn() {
		return this.expiresIn;
	}

	public void setExpiresIn(Date expiresIn) {
		this.expiresIn = expiresIn;
	}

	@Column(name = "uid", nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

}
