package com.itucity.dsmp.identity.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserDetailPO generated by hbm2java
 */
@Entity
@Table(name = "bs_user_detail")
public class UserDetailPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2699596578077620243L;
	private Integer uid;
	private Integer sex;
	private String realName;
	private String nickName;
	private String country;
	private String province;
	private String city;
	private String language;
	private String idcard;
	private Date registerTime;
	private Integer imageId;

	public UserDetailPO() {
	}

	public UserDetailPO(Integer uid) {
		this.uid = uid;
	}

	public UserDetailPO(Integer uid, Integer sex, String realName, String nickName,
			String country, String province, String city, String language,
			String idcard, Date registerTime, Integer imageId) {
		this.uid = uid;
		this.sex = sex;
		this.realName = realName;
		this.nickName = nickName;
		this.country = country;
		this.province = province;
		this.city = city;
		this.language = language;
		this.idcard = idcard;
		this.registerTime = registerTime;
		this.imageId = imageId;
	}

	@Id
	@Column(name = "uid", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Column(name = "real_name", length = 18)
	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	@Column(name = "nick_name", length = 18)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "country", length = 18)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "province", length = 18)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "city", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "language", length = 30)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "idcard", length = 20)
	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_time", length = 19)
	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	@Column(name = "image_id")
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

}
