package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccessLogPO generated by hbm2java
 */
@Entity
@Table(name = "tw_access_log", catalog = "dsmp")
public class AccessLogPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4664905643888651914L;
	private Integer id;
	private String ipAddress;
	private String fromClient;
	private Integer uid;
	private Date accessTime;
	private String weatherCode;

	public AccessLogPO() {
	}

	public AccessLogPO(String ipAddress, String fromClient, Integer uid,
			Date accessTime, String weatherCode) {
		this.ipAddress = ipAddress;
		this.fromClient = fromClient;
		this.uid = uid;
		this.accessTime = accessTime;
		this.weatherCode = weatherCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ip_address", length = 18)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "from_client", length = 18)
	public String getFromClient() {
		return this.fromClient;
	}

	public void setFromClient(String fromClient) {
		this.fromClient = fromClient;
	}

	@Column(name = "uid")
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "access_time", length = 19)
	public Date getAccessTime() {
		return this.accessTime;
	}

	public void setAccessTime(Date accessTime) {
		this.accessTime = accessTime;
	}

	@Column(name = "weather_code", length = 20)
	public String getWeatherCode() {
		return this.weatherCode;
	}

	public void setWeatherCode(String weatherCode) {
		this.weatherCode = weatherCode;
	}

}
