package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AreaPO generated by hbm2java
 */
@Entity
@Table(name = "bs_area", catalog = "dsmp")
public class AreaPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3912236321328689138L;
	private Integer areaId;
	private String areaName;
	private Integer parentId;
	private Integer sort;

	public AreaPO() {
	}

	public AreaPO(String areaName, Integer parentId, Integer sort) {
		this.areaName = areaName;
		this.parentId = parentId;
		this.sort = sort;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "area_id", unique = true, nullable = false)
	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	@Column(name = "area_name", length = 18)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "sort")
	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

}
