package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FeedbackTypePO generated by hbm2java
 */
@Entity
@Table(name = "tw_feedback_type", catalog = "dsmp")
public class FeedbackTypePO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3973124941313816688L;
	private Integer typeId;
	private String typeName;

	public FeedbackTypePO() {
	}

	public FeedbackTypePO(String typeName) {
		this.typeName = typeName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "type_id", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "type_name", length = 20)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
