package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * ImagePO generated by hbm2java
 */
@Entity
@Table(name = "tw_image", catalog = "dsmp")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class ImagePO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9090555835148073060L;
	private Integer imageId;
	private String title;
	private String description;
	private String raw;
	private Integer rawHeight;
	private Integer rawWidth;
	private String large;
	private String medium;
	private String small;
	private String mini;
	private String square;
	private String hash;
	private String extension;
	private Date createTime;
	private Integer isPrivate;
	private Integer uid;
	private String purpose;
	private Integer rawSize;

	public ImagePO() {
	}

	public ImagePO(String title, String description, String raw,
			Integer rawHeight, Integer rawWidth, String large, String medium,
			String small, String mini, String square, String hash,
			String extension, Date createTime, Integer isPrivate, Integer uid,
			String purpose, Integer rawSize) {
		this.title = title;
		this.description = description;
		this.raw = raw;
		this.rawHeight = rawHeight;
		this.rawWidth = rawWidth;
		this.large = large;
		this.medium = medium;
		this.small = small;
		this.mini = mini;
		this.square = square;
		this.hash = hash;
		this.extension = extension;
		this.createTime = createTime;
		this.isPrivate = isPrivate;
		this.uid = uid;
		this.purpose = purpose;
		this.rawSize = rawSize;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "image_id", unique = true, nullable = false)
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Lob
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "raw")
	public String getRaw() {
		return this.raw;
	}

	public void setRaw(String raw) {
		this.raw = raw;
	}

	@Column(name = "raw_height")
	public Integer getRawHeight() {
		return this.rawHeight;
	}

	public void setRawHeight(Integer rawHeight) {
		this.rawHeight = rawHeight;
	}

	@Column(name = "raw_width")
	public Integer getRawWidth() {
		return this.rawWidth;
	}

	public void setRawWidth(Integer rawWidth) {
		this.rawWidth = rawWidth;
	}

	@Column(name = "large")
	public String getLarge() {
		return this.large;
	}

	public void setLarge(String large) {
		this.large = large;
	}

	@Column(name = "medium")
	public String getMedium() {
		return this.medium;
	}

	public void setMedium(String medium) {
		this.medium = medium;
	}

	@Column(name = "small")
	public String getSmall() {
		return this.small;
	}

	public void setSmall(String small) {
		this.small = small;
	}

	@Column(name = "mini")
	public String getMini() {
		return this.mini;
	}

	public void setMini(String mini) {
		this.mini = mini;
	}

	@Column(name = "square")
	public String getSquare() {
		return this.square;
	}

	public void setSquare(String square) {
		this.square = square;
	}

	@Column(name = "hash")
	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	@Column(name = "extension", length = 20)
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "is_private")
	public Integer getIsPrivate() {
		return this.isPrivate;
	}

	public void setIsPrivate(Integer isPrivate) {
		this.isPrivate = isPrivate;
	}

	@Column(name = "uid")
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "purpose", length = 20)
	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	@Column(name = "raw_size")
	public Integer getRawSize() {
		return this.rawSize;
	}

	public void setRawSize(Integer rawSize) {
		this.rawSize = rawSize;
	}

}
