package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LineScore generated by hbm2java
 */
@Entity
@Table(name = "tw_line_score", catalog = "dsmp")
public class LineScore implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3442614099069828744L;
	private LineScoreId id;
	private Integer score;

	public LineScore() {
	}

	public LineScore(LineScoreId id) {
		this.id = id;
	}

	public LineScore(LineScoreId id, Integer score) {
		this.id = id;
		this.score = score;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "uid", column = @Column(name = "uid", nullable = false)),
			@AttributeOverride(name = "lineId", column = @Column(name = "line_id", nullable = false)) })
	public LineScoreId getId() {
		return this.id;
	}

	public void setId(LineScoreId id) {
		this.id = id;
	}

	@Column(name = "score")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

}
