package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Lob;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LineCustomPO generated by hbm2java
 */
@Entity
@Table(name = "tw_line_custom", catalog = "dsmp")
public class LineCustomPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4422748466815254802L;
	private Integer lineId;
	private String title;
	private String description;
	private Integer uid;
	private Integer imageId;

	public LineCustomPO() {
	}

	public LineCustomPO(String title, String description, Integer uid,
			Integer imageId) {
		this.title = title;
		this.description = description;
		this.uid = uid;
		this.imageId = imageId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "line_id", unique = true, nullable = false)
	public Integer getLineId() {
		return this.lineId;
	}

	public void setLineId(Integer lineId) {
		this.lineId = lineId;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Lob
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "uid")
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "image_id")
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

}
