package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LinePlacePOId generated by hbm2java
 */
@Embeddable
public class LinePlacePOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8795399481622662010L;
	private Integer placeId;
	private Integer lineId;

	public LinePlacePOId() {
	}

	public LinePlacePOId(Integer placeId, Integer lineId) {
		this.placeId = placeId;
		this.lineId = lineId;
	}

	@Column(name = "place_id", nullable = false)
	public Integer getPlaceId() {
		return this.placeId;
	}

	public void setPlaceId(Integer placeId) {
		this.placeId = placeId;
	}

	@Column(name = "line_id", nullable = false)
	public Integer getLineId() {
		return this.lineId;
	}

	public void setLineId(Integer lineId) {
		this.lineId = lineId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LinePlacePOId))
			return false;
		LinePlacePOId castOther = (LinePlacePOId) other;

		return (this.getPlaceId() == castOther.getPlaceId())
				&& (this.getLineId() == castOther.getLineId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlaceId();
		result = 37 * result + this.getLineId();
		return result;
	}

}
