package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LineTagPOId generated by hbm2java
 */
@Embeddable
public class LineTagPOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7804118754920654296L;
	private Integer lineId;
	private Integer tagId;

	public LineTagPOId() {
	}

	public LineTagPOId(Integer lineId, Integer tagId) {
		this.lineId = lineId;
		this.tagId = tagId;
	}

	@Column(name = "line_id", nullable = false)
	public Integer getLineId() {
		return this.lineId;
	}

	public void setLineId(Integer lineId) {
		this.lineId = lineId;
	}

	@Column(name = "tag_id", nullable = false)
	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineTagPOId))
			return false;
		LineTagPOId castOther = (LineTagPOId) other;

		return (this.getLineId() == castOther.getLineId())
				&& (this.getTagId() == castOther.getTagId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLineId();
		result = 37 * result + this.getTagId();
		return result;
	}

}
