package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LineOnLoadPO generated by hbm2java
 */
@Entity
@Table(name = "tw_line_on_road", catalog = "dsmp")
public class LineOnLoadPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8037863289084297029L;
	private Integer id;
	private Integer lineId;
	private Integer uid;
	private Date createTime;
	private Integer isActive;
	private Date modifyTime;

	public LineOnLoadPO() {
	}

	public LineOnLoadPO(Integer lineId, Integer uid) {
		this.lineId = lineId;
		this.uid = uid;
	}

	public LineOnLoadPO(Integer lineId, Integer uid, Date createTime, Integer isActive,
			Date modifyTime) {
		this.lineId = lineId;
		this.uid = uid;
		this.createTime = createTime;
		this.isActive = isActive;
		this.modifyTime = modifyTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "line_id", nullable = false)
	public Integer getLineId() {
		return this.lineId;
	}

	public void setLineId(Integer lineId) {
		this.lineId = lineId;
	}

	@Column(name = "uid", nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "is_active")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
