package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LineScoreId generated by hbm2java
 */
@Embeddable
public class LineScoreId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7532131394982858205L;
	private Integer uid;
	private Integer lineId;

	public LineScoreId() {
	}

	public LineScoreId(Integer uid, Integer lineId) {
		this.uid = uid;
		this.lineId = lineId;
	}

	@Column(name = "uid", nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "line_id", nullable = false)
	public Integer getLineId() {
		return this.lineId;
	}

	public void setLineId(Integer lineId) {
		this.lineId = lineId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineScoreId))
			return false;
		LineScoreId castOther = (LineScoreId) other;

		return (this.getUid() == castOther.getUid())
				&& (this.getLineId() == castOther.getLineId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUid();
		result = 37 * result + this.getLineId();
		return result;
	}

}
