package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LineTagPO generated by hbm2java
 */
@Entity
@Table(name = "tw_line_tag", catalog = "dsmp")
public class LineTagPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9135966746577599347L;
	private LineTagPOId id;

	public LineTagPO() {
	}

	public LineTagPO(LineTagPOId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "lineId", column = @Column(name = "line_id", nullable = false)),
			@AttributeOverride(name = "tagId", column = @Column(name = "tag_id", nullable = false)) })
	public LineTagPOId getId() {
		return this.id;
	}

	public void setId(LineTagPOId id) {
		this.id = id;
	}

}
