package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LineImagePOId generated by hbm2java
 */
@Embeddable
public class LineImagePOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6933445158895756052L;
	private Integer lineId;
	private Integer imageId;

	public LineImagePOId() {
	}

	public LineImagePOId(Integer lineId, Integer imageId) {
		this.lineId = lineId;
		this.imageId = imageId;
	}

	@Column(name = "line_id", nullable = false)
	public Integer getLineId() {
		return this.lineId;
	}

	public void setLineId(Integer lineId) {
		this.lineId = lineId;
	}

	@Column(name = "image_id", nullable = false)
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineImagePOId))
			return false;
		LineImagePOId castOther = (LineImagePOId) other;

		return (this.getLineId() == castOther.getLineId())
				&& (this.getImageId() == castOther.getImageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLineId();
		result = 37 * result + this.getImageId();
		return result;
	}

}
