package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LinePlacePO generated by hbm2java
 */
@Entity
@Table(name = "tw_line_place", catalog = "dsmp")
public class LinePlacePO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3471351692022880059L;
	private LinePlacePOId id;
	
	private Integer sort;

	public LinePlacePO() {
	}

	public LinePlacePO(LinePlacePOId id, Integer sort) {
		this.id = id;
		this.sort = sort;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "placeId", column = @Column(name = "place_id", nullable = false)),
			@AttributeOverride(name = "lineId", column = @Column(name = "line_id", nullable = false)) })
	public LinePlacePOId getId() {
		return this.id;
	}

	public void setId(LinePlacePOId id) {
		this.id = id;
	}

	@Column(name = "sort")
	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}
	
	

}
