package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LineCommentPO generated by hbm2java
 */
@Entity
@Table(name = "tw_line_comment", catalog = "dsmp")
public class LineCommentPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3526325453087405756L;
	private Integer commentId;
	private String content;
	private Date createTime;
	private Date modifyTime;
	private Integer commentParentId;
	private Integer uid;
	private Integer lineId;

	public LineCommentPO() {
	}

	public LineCommentPO(Integer uid, Integer lineId) {
		this.uid = uid;
		this.lineId = lineId;
	}

	public LineCommentPO(String content, Date createTime, Date modifyTime,
			Integer commentParentId, Integer uid, Integer lineId) {
		this.content = content;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.commentParentId = commentParentId;
		this.uid = uid;
		this.lineId = lineId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "comment_id", unique = true, nullable = false)
	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	@Lob
	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "comment_parent_id")
	public Integer getCommentParentId() {
		return this.commentParentId;
	}

	public void setCommentParentId(Integer commentParentId) {
		this.commentParentId = commentParentId;
	}

	@Column(name = "uid", nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "line_id", nullable = false)
	public Integer getLineId() {
		return this.lineId;
	}

	public void setLineId(Integer lineId) {
		this.lineId = lineId;
	}

}
