package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PlaceScorePO generated by hbm2java
 */
@Entity
@Table(name = "tw_place_score", catalog = "dsmp")
public class PlaceScorePO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3093033570694272892L;
	private PlaceScorePOId id;
	private Integer score;

	public PlaceScorePO() {
	}

	public PlaceScorePO(PlaceScorePOId id) {
		this.id = id;
	}

	public PlaceScorePO(PlaceScorePOId id, Integer score) {
		this.id = id;
		this.score = score;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "placeId", column = @Column(name = "place_id", nullable = false)),
			@AttributeOverride(name = "uid", column = @Column(name = "uid", nullable = false)) })
	public PlaceScorePOId getId() {
		return this.id;
	}

	public void setId(PlaceScorePOId id) {
		this.id = id;
	}

	@Column(name = "score")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

}
