package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlaceCollectPO generated by hbm2java
 */
@Entity
@Table(name = "tw_place_collect", catalog = "dsmp")
public class PlaceCollectPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 611042652584330443L;
	private Integer id;
	private Integer uid;
	private Date createTime;
	private Integer placeId;

	public PlaceCollectPO() {
	}

	public PlaceCollectPO(Integer uid, Date createTime, Integer placeId) {
		this.uid = uid;
		this.createTime = createTime;
		this.placeId = placeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "uid")
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "place_id")
	public Integer getPlaceId() {
		return this.placeId;
	}

	public void setPlaceId(Integer placeId) {
		this.placeId = placeId;
	}

}
