package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlaceSocialCountPO generated by hbm2java
 */
@Entity
@Table(name = "tw_place_social_count", catalog = "dsmp")
public class PlaceSocialCountPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -972844172949687482L;
	private Integer placeId;
	private Integer favoriteCount;
	private Integer shareCount;
	private Integer collectCount;
	private Integer commentId;
	private Integer hateCount;
	private Integer viewCount;

	public PlaceSocialCountPO() {
	}

	public PlaceSocialCountPO(Integer placeId) {
		this.placeId = placeId;
	}

	public PlaceSocialCountPO(Integer placeId, Integer favoriteCount,
			Integer shareCount, Integer collectCount, Integer commentId,
			Integer hateCount, Integer viewCount) {
		this.placeId = placeId;
		this.favoriteCount = favoriteCount;
		this.shareCount = shareCount;
		this.collectCount = collectCount;
		this.commentId = commentId;
		this.hateCount = hateCount;
		this.viewCount = viewCount;
	}

	@Id
	@Column(name = "place_id", unique = true, nullable = false)
	public Integer getPlaceId() {
		return this.placeId;
	}

	public void setPlaceId(Integer placeId) {
		this.placeId = placeId;
	}

	@Column(name = "favorite_count")
	public Integer getFavoriteCount() {
		return this.favoriteCount;
	}

	public void setFavoriteCount(Integer favoriteCount) {
		this.favoriteCount = favoriteCount;
	}

	@Column(name = "share_count")
	public Integer getShareCount() {
		return this.shareCount;
	}

	public void setShareCount(Integer shareCount) {
		this.shareCount = shareCount;
	}

	@Column(name = "collect_count")
	public Integer getCollectCount() {
		return this.collectCount;
	}

	public void setCollectCount(Integer collectCount) {
		this.collectCount = collectCount;
	}

	@Column(name = "comment_id")
	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	@Column(name = "hate_count")
	public Integer getHateCount() {
		return this.hateCount;
	}

	public void setHateCount(Integer hateCount) {
		this.hateCount = hateCount;
	}

	@Column(name = "view_count")
	public Integer getViewCount() {
		return this.viewCount;
	}

	public void setViewCount(Integer viewCount) {
		this.viewCount = viewCount;
	}

}
