package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * PlacePO generated by hbm2java
 */
@Entity
@Table(name = "tw_place", catalog = "dsmp")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class PlacePO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2974410016986126708L;
	private Integer placeId;
	private Date createTime;
	private Date modifyTime;
	private String title;
	private String address;
	private String areaCode;
	private String contact;
	private String content;
	private Float longitude;
	private Float latitude;
	private Float price;
	private String tips;
	private String timeStart;
	private String timeEnd;
	private String timeDesc;
	private String scene;
	private String location;
	private Integer duration;

	public PlacePO() {
	}

	public PlacePO(Date createTime, Date modifyTime, String title,
			String address, String areaCode, String contact, String content,
			Float longitude, Float latitude, Float price, String tips,
			String timeStart, String timeEnd, String timeDesc, String scene,
			String location, Integer duration) {
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.title = title;
		this.address = address;
		this.areaCode = areaCode;
		this.contact = contact;
		this.content = content;
		this.longitude = longitude;
		this.latitude = latitude;
		this.price = price;
		this.tips = tips;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.timeDesc = timeDesc;
		this.scene = scene;
		this.location = location;
		this.duration = duration;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "place_id", unique = true, nullable = false)
	public Integer getPlaceId() {
		return this.placeId;
	}

	public void setPlaceId(Integer placeId) {
		this.placeId = placeId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "area_code", length = 18)
	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "contact", length = 50)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Lob
	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "longitude", precision = 12, scale = 0)
	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", precision = 12, scale = 0)
	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "tips")
	public String getTips() {
		return this.tips;
	}

	public void setTips(String tips) {
		this.tips = tips;
	}

	@Column(name = "time_start", length = 19)
	public String getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(String timeStart) {
		this.timeStart = timeStart;
	}

	@Column(name = "time_end", length = 19)
	public String getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(String timeEnd) {
		this.timeEnd = timeEnd;
	}

	@Column(name = "time_desc", length = 255)
	public String getTimeDesc() {
		return this.timeDesc;
	}

	public void setTimeDesc(String timeDesc) {
		this.timeDesc = timeDesc;
	}

	@Column(name = "scene", length = 30)
	public String getScene() {
		return this.scene;
	}

	public void setScene(String scene) {
		this.scene = scene;
	}

	@Column(name = "location", length = 30)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

}
