package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlaceTagPOId generated by hbm2java
 */
@Embeddable
public class PlaceTagPOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3042403084403915009L;
	private Integer placeId;
	private Integer tagId;

	public PlaceTagPOId() {
	}

	public PlaceTagPOId(Integer placeId, Integer tagId) {
		this.placeId = placeId;
		this.tagId = tagId;
	}

	@Column(name = "place_id", nullable = false)
	public Integer getPlaceId() {
		return this.placeId;
	}

	public void setPlaceId(Integer placeId) {
		this.placeId = placeId;
	}

	@Column(name = "tag_id", nullable = false)
	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlaceTagPOId))
			return false;
		PlaceTagPOId castOther = (PlaceTagPOId) other;

		return (this.getPlaceId() == castOther.getPlaceId())
				&& (this.getTagId() == castOther.getTagId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlaceId();
		result = 37 * result + this.getTagId();
		return result;
	}

}
