package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlaceScorePOId generated by hbm2java
 */
@Embeddable
public class PlaceScorePOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1903957654117874346L;
	private Integer placeId;
	private Integer uid;

	public PlaceScorePOId() {
	}

	public PlaceScorePOId(Integer placeId, Integer uid) {
		this.placeId = placeId;
		this.uid = uid;
	}

	@Column(name = "place_id", nullable = false)
	public Integer getPlaceId() {
		return this.placeId;
	}

	public void setPlaceId(Integer placeId) {
		this.placeId = placeId;
	}

	@Column(name = "uid", nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlaceScorePOId))
			return false;
		PlaceScorePOId castOther = (PlaceScorePOId) other;

		return (this.getPlaceId() == castOther.getPlaceId())
				&& (this.getUid() == castOther.getUid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlaceId();
		result = 37 * result + this.getUid();
		return result;
	}

}
