package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlaceImagePOId generated by hbm2java
 */
@Embeddable
public class PlaceImagePOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -988387901437800717L;
	private Integer imageId;
	private Integer placeId;

	public PlaceImagePOId() {
	}

	public PlaceImagePOId(Integer imageId, Integer placeId) {
		this.imageId = imageId;
		this.placeId = placeId;
	}

	@Column(name = "image_id", nullable = false)
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	@Column(name = "place_id", nullable = false)
	public Integer getPlaceId() {
		return this.placeId;
	}

	public void setPlaceId(Integer placeId) {
		this.placeId = placeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlaceImagePOId))
			return false;
		PlaceImagePOId castOther = (PlaceImagePOId) other;

		return (this.getImageId() == castOther.getImageId())
				&& (this.getPlaceId() == castOther.getPlaceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getImageId();
		result = 37 * result + this.getPlaceId();
		return result;
	}

}
