package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SearchHistoryPO generated by hbm2java
 */
@Entity
@Table(name = "tw_search_history", catalog = "dsmp")
public class SearchHistoryPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7659598696762120771L;
	private Integer docId;
	private String content;
	private Date createTime;
	private Integer uid;
	private String searchResult;
	private Integer used;

	public SearchHistoryPO() {
	}

	public SearchHistoryPO(String content, Date createTime, Integer uid,
			String searchResult, Integer used) {
		this.content = content;
		this.createTime = createTime;
		this.uid = uid;
		this.searchResult = searchResult;
		this.used = used;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "doc_id", unique = true, nullable = false)
	public Integer getDocId() {
		return this.docId;
	}

	public void setDocId(Integer docId) {
		this.docId = docId;
	}

	@Lob
	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "uid")
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}
	
	@Lob
	@Column(name = "search_result")
	public String getSearchResult() {
		return this.searchResult;
	}

	public void setSearchResult(String searchResult) {
		this.searchResult = searchResult;
	}

	@Column(name = "used")
	public Integer getUsed() {
		return this.used;
	}

	public void setUsed(Integer used) {
		this.used = used;
	}

}
