package com.itucity.dsmp.tripwiki.dao.entity;
// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WeatherPO generated by hbm2java
 */
@Entity
@Table(name = "bs_weahter", catalog = "dsmp")
public class WeatherPO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7265747815066512629L;
	private String weatherCode;
	private String weatherName;

	public WeatherPO() {
	}

	public WeatherPO(String weatherCode) {
		this.weatherCode = weatherCode;
	}

	public WeatherPO(String weatherCode, String weatherName) {
		this.weatherCode = weatherCode;
		this.weatherName = weatherName;
	}

	@Id
	@Column(name = "weather_code", unique = true, nullable = false, length = 20)
	public String getWeatherCode() {
		return this.weatherCode;
	}

	public void setWeatherCode(String weatherCode) {
		this.weatherCode = weatherCode;
	}

	@Column(name = "weather_name", length = 30)
	public String getWeatherName() {
		return this.weatherName;
	}

	public void setWeatherName(String weatherName) {
		this.weatherName = weatherName;
	}

}
