package com.itucity.dsmp.tripwiki.dao.entity;

// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WxToken generated by hbm2java
 */
@Entity
@Table(name = "wx_token", catalog = "dsmp")
public class WxToken implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1317290772293103517L;
	private Integer tokenId;
	private String accessToken;
	private String refreshToken;
	private Date expiresIn;

	public WxToken() {
	}

	public WxToken(String accessToken, String refreshToken, Date expiresIn) {
		this.accessToken = accessToken;
		this.refreshToken = refreshToken;
		this.expiresIn = expiresIn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "token_id", unique = true, nullable = false)
	public Integer getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(Integer tokenId) {
		this.tokenId = tokenId;
	}

	@Column(name = "access_token", length = 30)
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Column(name = "refresh_token", length = 30)
	public String getRefreshToken() {
		return this.refreshToken;
	}

	public void setRefreshToken(String refreshToken) {
		this.refreshToken = refreshToken;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expires_in", length = 19)
	public Date getExpiresIn() {
		return this.expiresIn;
	}

	public void setExpiresIn(Date expiresIn) {
		this.expiresIn = expiresIn;
	}

}
