package com.itucity.dsmp.tripwiki.dto;

// default package
// Generated 2014-4-13 11:00:07 by Hibernate Tools 3.4.0.CR1

/**
 * AreaPO generated by hbm2java
 */
public class AreaVO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3912236321328689138L;
	private Integer areaId;
	private String areaName;
	private Integer parentId;
	private Integer sort;

	public AreaVO() {
	}

	public AreaVO(String areaName, Integer parentId, Integer sort) {
		this.areaName = areaName;
		this.parentId = parentId;
		this.sort = sort;
	}

	public Integer getAreaId() {
		return areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

}
